aspnet/Performance

- test/Microsoft.AspNet.Tests.Performance.Utility/Helpers/DnuHelper.cs
- test/Microsoft.AspNet.Tests.Performance.Utility/Logging/LoggerHelper.cs
- test/Microsoft.AspNet.Tests.Performance.Utility/Logging/TeamcityLogger.cs
- test/Microsoft.AspNet.Tests.Performance.Utility/Measurement/ConsoleAppStartup.cs
- test/Microsoft.AspNet.Tests.Performance.Utility/Measurement/Repeater.cs
- test/Microsoft.AspNet.Tests.Performance.Utility/Measurement/StartupRunnerOptions.cs
- test/Microsoft.AspNet.Tests.Performance.Utility/Measurement/Statistic.cs
- test/Microsoft.AspNet.Tests.Performance.Utility/Measurement/WebApplicationFirstRequest.cs
- test/Microsoft.AspNet.Tests.Performance/BasicStartup.cs
> Run multiple iterations in one run and report the mean

- testapp/StartWebApi/project.json
https://github.com/aspnet/dnx/issues/1474
@troydai
> Rename "dnu bundle" to "dnu publish"

- dashboard/PerformanceDashboard/appsettings.json
- testapp/StarterMvc/appsettings.json
Reacting to https://github.com/aspnet/Logging/pull/314.
Need to test locally.
> Reacting to verbose rename

- src/Stress.Framework/IStressMetricReporter.cs
- src/Stress.Framework/ITestProgressMessage.cs
- src/Stress.Framework/ITestStatisticsMessage.cs
- src/Stress.Framework/StressConfig.cs
- src/Stress.Framework/StressRunSummary.cs
- src/Stress.Framework/StressTeamCityReporter.cs
- src/Stress.Framework/StressTestCase.cs
- src/Stress.Framework/StressTestCaseRunner.cs
- src/Stress.Framework/StressTestProgressMessage.cs
- src/Stress.Framework/StressTestStatisticsMessage.cs
- src/Stress.Framework/StressTestTeamCityReporterMessageHandler.cs
- src/Stress.Framework/TimedMetricReporter.cs
- stress-test/Microsoft.AspNet.Tests.Stress/config.json
> Add metric output support

- makefile.shade
- src/Stress.Framework/StressAttribute.cs
- src/Stress.Framework/StressMetricCollector.cs
- src/Stress.Framework/StressTestCase.cs
- src/Stress.Framework/StressTestCaseBase.cs
- src/Stress.Framework/StressTestCaseDiscoverer.cs
- src/Stress.Framework/StressTestCaseRunner.cs
- src/Stress.Framework/StressTestServer.cs
- src/Stress.Framework/project.json
- testapp/StarterMvc/wwwroot/_references.js
Depends on https://github.com/aspnet/Hosting/pull/560
@NTaylorMullen
> Add IIS support

- src/Benchmarks.Utility/Helpers/DotnetHelper.cs
- src/Benchmarks.Utility/Helpers/TestSampleManager.cs
- test/Microsoft.AspNet.Tests.Performance/PublishTests.cs
> Adding publish performance tests

- test/Microbenchmarks.Tests/RazorTests.cs
> React to Fileprovider namespace changes

- src/Stress.Framework/ITestSummaryStatisticsMessage.cs
- src/Stress.Framework/StressAttribute.cs
- src/Stress.Framework/StressConfig.cs
- src/Stress.Framework/StressMetricCollector.cs
- src/Stress.Framework/StressRunSummary.cs
- src/Stress.Framework/StressTestBase.cs
- src/Stress.Framework/StressTestCase.cs
- src/Stress.Framework/StressTestCaseDiscoverer.cs
- src/Stress.Framework/StressTestCaseRunner.cs
- src/Stress.Framework/StressTestSummaryStatisticsMessage.cs
- src/Stress.Framework/StressTestTeamCityReporterMessageHandler.cs
- src/Stress.Framework/TimedMetricReporter.cs
And optional statistic to file logging
@NTaylorMullen
> Add multi threaded stress test support

- src/Benchmarks.Utility/project.json
- testapp/BasicKestrelJson/project.json
- testapp/MediumApi/project.json
> Updated Json.Net versions

- README.md
Usability improvement. This is just to make it easier for users to ramp up on this repository.
@muratg
> Adding repository dependencies to README.md

- testapp/HelloWorldMvc/loadtest.ps1
> Adding loadtest script for HelloWorldMvc

- stress-test/Microsoft.AspNetCore.Tests.Stress/StarterMvcTests.cs
- stress-test/Microsoft.AspNetCore.Tests.Stress/project.json
- tools/LargePageGenerator/project.json
- tools/ThroughputResultReporter/project.json
@JunTaoLuo @muratg @SajayAntony 
Adding packages that unblock building stress-test under the CLI.
> Fixes the build of the stress test project

- README.md
Readme update basically showing how get to the micro benchmark and run them. @muratg @rynowak @DavidObando
> Add instructions for running microbenchmark tests.

- testapp/BasicKestrel/Startup.cs
- testapp/BasicKestrel/loadtest.ps1
Test script for load generated in https://github.com/aspnet/KestrelHttpServer/issues/610#issuecomment-183573194 and https://github.com/aspnet/KestrelHttpServer/issues/580#issuecomment-183571249
> Tests script for BasicKestrel loadtest

- README.md
I created a VM in Azure and went through these instructions. Had to make some adjustments.
> Revision to Ubuntu requirements documentation

- makefile.shade
- src/Benchmarks.Utility/project.json
- test/TestApp.Test/project.json
> Update makefile and project.json to fix build

- testapp/BasicViews/BasicViewsContext.cs
- testapp/BasicViews/Controllers/HomeController.cs
- testapp/BasicViews/Person.cs
- testapp/BasicViews/Startup.cs
- testapp/BasicViews/Views/Shared/_Layout.cshtml
- testapp/BasicViews/appsettings.json
- testapp/BasicViews/project.json
- testapp/BasicViews/wwwroot/web.config
- Remove DNX
- Add EF + LocalDB
- Make Layout more like our template
Completes the requirements for building out https://github.com/aspnet/Mvc/issues/4175
> Updates to BasicViews

- test/Reliability/BasicKestrel/ReadMe.md
- testapp/StressMvc/ReadMe.md
> Fixed Formatting to run stress test and links to clients

- testapp/BasicApi/project.json
- testapp/BasicKestrel/project.json
- testapp/BasicKestrelJson/project.json
- testapp/BigModelBinding/project.json
- testapp/BigViews/project.json
- testapp/HelloWorldMvc/project.json
- testapp/KestrelLargeStaticFile/project.json
- testapp/LargePageMvc/project.json
- testapp/LargeStaticView/project.json
- testapp/LocalizedViews/project.json
- testapp/PlainTextMvc/project.json
- testapp/PooledKestrel/project.json
- testapp/RazorCodeGenerator/project.json
- testapp/StarterMvc/project.json
@rynowak  - Fixing up dnx in the micro benchmarks under testapp
> Update dnx451 to net451 for microbenchmarks.

- test/ColdStart/InstallDotnet.ps1
> Cleanup install dotnet for coldstart.

- testapp/MultipartPOST/MultipartPOST/Controllers/UploadController.cs
The previous implementation relied on manually reading the body and using a MultipartReader object in order to fully consume all the parts and read all the bytes. This is actually redundant as ASP.NET has a built-in feature where multiparts are read and cached in a local file even before the controller is called. All the controller has to do is either specify a complex object as its parameter or access the files via the Request.Form object.
> MultipartPost test now uses the form feature

- testapp/BasicApi/project.json
- testapp/BasicKestrel/project.json
- testapp/BasicKestrelJson/project.json
- testapp/BasicViews/project.json
- testapp/BigModelBinding/project.json
- testapp/BigViews/project.json
- testapp/HelloWorldMvc/project.json
- testapp/LargePageMvc/project.json
- testapp/LargeStaticView/project.json
- testapp/LocalizedViews/project.json
- testapp/MultipartPOST/MultipartPOST/project.json
- testapp/MultipartPOST/MultipartPOSTClient/project.json
- testapp/PlainTextMvc/project.json
- testapp/PooledKestrel/project.json
- testapp/RazorCodeGenerator/project.json
- testapp/StarterMvc/project.json
- testapp/StressMvc/project.json
@halter73 @rynowak  @mnltejaswini
> Move to Netstandard.Librarby:1.5.0 for testapp

- dashboard/PerformanceDashboard/Startup.cs
- dashboard/PerformanceDashboard/project.json
- testapp/BasicKestrel/Startup.cs
- testapp/BasicKestrel/project.json
- testapp/BasicKestrel/wwwroot/web.config
- testapp/BasicKestrelJson/Startup.cs
- testapp/BasicKestrelJson/project.json
- testapp/BasicViews/Startup.cs
- testapp/BasicViews/project.json
- testapp/BigViews/Startup.cs
- testapp/BigViews/project.json
- testapp/HelloWorldMvc/Startup.cs
- testapp/HelloWorldMvc/project.json
- testapp/HelloWorldMvc/wwwroot/web.config
- testapp/KestrelLargeStaticFile/Startup.cs
- testapp/KestrelLargeStaticFile/project.json
- testapp/LargePageMvc/Startup.cs
- testapp/LargePageMvc/project.json
- testapp/MultipartPOST/MultipartPOST/Startup.cs
- testapp/MultipartPOST/MultipartPOST/project.json
- testapp/PlainTextMvc/Startup.cs
- testapp/PlainTextMvc/project.json
- testapp/PooledKestrel/Startup.cs
- testapp/PooledKestrel/project.json
- testapp/StarterMvc/Startup.cs
- testapp/StarterMvc/project.json
- testapp/StressMvc/Startup.cs
- testapp/StressMvc/project.json
> Use new AspnetCore module in place of old platform handler

- test/ColdStart/Measure.ps1
- test/ColdStart/Publish.ps1
- test/ColdStart/README.md
- test/ColdStart/SetEnv.ps1
Minor fixes and updates to make sure we can run the script from anywhere.
> Fixed scripts to remove toolspath and resort to environment variable.

- testapp/BasicApi/project.json
- testapp/BasicKestrel/project.json
- testapp/BasicKestrelJson/project.json
- testapp/BasicViews/project.json
- testapp/BigModelBinding/project.json
- testapp/BigViews/project.json
- testapp/HelloWorldMvc/project.json
- testapp/HelloWorldMvcCore/project.json
- testapp/KestrelLargeStaticFile/project.json
- testapp/LargePageMvc/project.json
- testapp/LargeStaticView/project.json
- testapp/LocalizedViews/project.json
- testapp/MultipartPOST/MultipartPOST/project.json
- testapp/PlainTextMvc/project.json
- testapp/PooledKestrel/project.json
- testapp/StarterMvc/project.json
- testapp/StressMvc/project.json
/cc @SajayAntony @DavidObando - can you think of a reason **not** to enable server GC for any of these projects?
> Enable server GC for all 'app' projects

- .travis.yml
- appveyor.yml
Looks like you missed one @natemcmaster
cc @DavidObando
> Limit the branches that build on our public CI like other repos

- src/Benchmarks.Utility/Helpers/SampleManager.cs
We're currently running tests that copy the test projects to a temporary directory, and then attempt to restore, build, and run from there. At this point, machines where a global nuget.config isn't configured will fail to restore these packages as most dependencies are actually provided by the feeds specified by this repo's NuGet.config file (at the root).
This change enables copying of NuGet.config to the temp folder where the test app has been copied to, and allows `dotnet restore` to succeed.
@sivagms @mnltejaswini @martinpf
> Copies the NuGet.config file to temp before restore

- test/Microbenchmarks.Tests/project.json
- test/Microsoft.AspNetCore.Tests.Performance/project.json
- test/TestApp.Test/project.json
- testapp/BasicKestrel/project.json
- testapp/BasicViews/project.json
- testapp/BigModelBinding/project.json
- testapp/BigViews/project.json
- testapp/HelloWorldMvc/project.json
- testapp/HelloWorldMvcCore/project.json
- testapp/LargePageMvc/project.json
- testapp/LargeStaticView/project.json
- testapp/LocalizedViews/project.json
- testapp/MultipartPOST/MultipartPOST/project.json
- testapp/StarterMvc/project.json
- testapp/StressMvc/project.json
> Adding "publishOptions" to complement "copyToOutput"

- test/ColdStart/Measure.ps1
- test/ColdStart/Measure.sh
Use the "urls" parameter name instead
> hostings has deprecated "server.urls" parameter name

- testapp/MultipartPOST/MultipartPOST/Controllers/UploadController.cs
- testapp/MultipartPOST/MultipartPOST/Startup.cs
- testapp/MultipartPOST/MultipartPOSTClient/Program.cs
- testapp/MultipartPOST/MultipartPOSTClient/RandomDataStreamContent.cs
- testapp/MultipartPOST/MultipartPOSTClient/project.json
- testapp/MultipartPOST/README.md
- testapp/MultipartPOST/runtest.ps1
Server:
- Exception printing middleware
- FormOptions set up
- Reporting filename for correlation purposes
Client:
- Proper handling of command line arguments
- Reporting filename for correlation purposes
- Adding line breaks on Riker Ipsum text.
- Faster implementation of RandomUtf8TextDataGenerator.Read method
PowerShell runner script:
- It now takes care of restoring and building before running
- 10 clients kicked off (3 second delay between each client)
- Clients and server now run on separate console windows
- Clients commanded to run for 100 iterations each
> Updates to MultipartPOST test

- testapp/KestrelShutdown/KestrelShutdown.xproj
- testapp/KestrelShutdown/Startup.cs
- testapp/KestrelShutdown/project.json
- testapp/KestrelShutdown/run-client.cmd
- testapp/KestrelShutdown/run-client.sh
- testapp/KestrelShutdown/run-server.cmd
- testapp/KestrelShutdown/run-server.sh
- testapp/KestrelShutdown/wwwroot/README.txt
- testapp/KestrelShutdown/wwwroot/web.config
This is intended to uncover problems when starting and stopping Kestrel is done repeatedly. A user might choose to restart Kestrel within the same process, or restart the process entirely. This code is currently restarting Kestrel within the same process but it's easi to modify this and test restarting the process instead.
@sivagms @martinpf
> Add test KestrelShutdown

- test/ColdStart/Archive-IIS.ps1
- test/ColdStart/Archive-nginx.sh
- test/ColdStart/Archive.ps1
- test/ColdStart/Archive.sh
- test/ColdStart/Artifacts/nginx-coldstart-services
- test/ColdStart/Measure-IIS.ps1
- test/ColdStart/Measure-nginx.sh
- test/ColdStart/Measure.ps1
- test/ColdStart/MeasureRequestLatency.ps1
- test/ColdStart/PerformTestAndProfile.sh
- test/ColdStart/Publish-IIS.ps1
- test/ColdStart/Publish.ps1
- test/ColdStart/Publish.sh
- test/ColdStart/README.md
- test/ColdStart/SetEnv.ps1
- test/ColdStart/SetEnv.sh
- test/Reliability/LinuxServerSetup.md
- testapp/BasicKestrel/wwwroot/web.config.net451
- testapp/HelloWorldMvc/wwwroot/web.config.net451
Included some fixes and extension of existing scripts and also added IIS scripts
> Cold start automation releated changes

- test/Microbenchmarks.Tests/HostingTests.cs
- fix test to actually use the `IServer` implementation
> React to `IServer` changes

- build/dependencies.props
- src/Benchmarks.Utility/Benchmarks.Utility.csproj
- src/Benchmarks.Utility/Helpers/IISTestManager.cs
- src/Stress.Framework/Stress.Framework.csproj
- src/Stress.Framework/StressTestServer.cs
As part of https://github.com/aspnet/Coherence/issues/190
> Updated to use 0.4.0 version of IntegrationTesting package

- testapp/StarterMvc/Models/ApplicationUser.cs
- testapp/StarterMvc/Startup.cs
- `IdentityRole` and `IdentityUser` moved to Microsoft.AspNetCore.Identity (from .EntityFrameworkCore)
> React to breaking changes

- build/common.props
- build/dependencies.props
- aspnet/Coherence-Signed#565
- continues work @kichalla did recently
> Always reference latest NETStandard.Library

- testapp/BasicApi/Startup.cs
> React to auth
